### ISSUE TITLE
Fazer botão de atualização de horários rodar quando clicado

### ISSUE THREAD

**Issue by jvfd3** [jvfd3/timetabling-UENF#240]
Seria algo assim
```css
@keyframes rotate {
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
}

.UpdateClassTimeIcon {
  color: #07eaff;
  transition: transform 0.5s;
}

.UpdateClassTimeIcon:active {
  animation: rotate 1s linear;
}
```

Ou assim

```css
.UpdateClassTimeIconRotating {
  animation: rotate 1s linear;
}
```

```javascript
import React, { useState } from 'react';

function MyComponent() {
  const [isRotating, setIsRotating] = useState(false);

  const handleClick = () => {
    setIsRotating(true);
    setTimeout(() => setIsRotating(false), 1000); // Remove the class after 1 second
  };

  return (
    <i
      className={`UpdateClassTimeIcon iconUpdate ${isRotating ? 'UpdateClassTimeIconRotating' : ''}`}
      onClick={handleClick}
    />
  );
}
```
